# line sensors
LINE_PINS = [18, 19, 20, 21]

# motors
LEFT_DIR_PIN = 4
LEFT_PWM_PIN = 5
RIGHT_DIR_PIN = 7
RIGHT_PWM_PIN = 6

START_BUTTON_PIN = 22 # button

# LEDs
LED_1_PIN = 12
LED_2_PIN = 14
LED_3_PIN = 16
LED_4_PIN = 17

# speed & duration configuration
BASE_SPEED = 1.0
REALIGN_MULTIPLIER = 0.4
OUTSIDE_TURN_SPEED = 1.0 * BASE_SPEED
INSIDE_TURN_SPEED = -0.5 * OUTSIDE_TURN_SPEED
TURN_AROUND_SPEED = 1.0 * BASE_SPEED
BAY_ENTER_SPEED = 0.7 * BASE_SPEED
RACK_APPROACH_SPEED = 0.7 * BASE_SPEED
BOX_DETECTING_SPEED = 0.8 * BASE_SPEED
WIGGLE_SPEED = 0.6 * BASE_SPEED
WIGGLE_DURATION = 250  # ms
LEFT_TURN_DURATION = int(880.0 / OUTSIDE_TURN_SPEED)
RIGHT_TURN_DURATION = int(840.0 / OUTSIDE_TURN_SPEED)
TURN_AROUND_DURATION = int(1320.0 / TURN_AROUND_SPEED)
BAY_ENTER_DURATION = int(920.0 / BAY_ENTER_SPEED)
RACK_APPROACH_DURATION = int(840.0 / RACK_APPROACH_SPEED)

# distance threshold for detecting a box
BAY_OCCUPIED_THRESHOLD_MM = 275

# distance sensors
I2C_ID_LEFT = 1
I2C_SDA_PIN_LEFT = 10
I2C_SCL_PIN_LEFT = 11
I2C_FREQ_LEFT = 400000
I2C_ID_RIGHT = 0
I2C_SDA_PIN_RIGHT = 8
I2C_SCL_PIN_RIGHT = 9
I2C_FREQ_RIGHT = 400000

# servos
JAW_SERVO_PIN = 13
TILT_SERVO_PIN = 15
SERVO_FREQ = 50

# ADC (resistance measurer)
ADC_PIN_NUMBER = 26
